services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    expose:
      - "80"
    depends_on:
      valkey:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/rag-diary?schema=public
      - OPENAI_API_KEY=sk-1234567890
      - VALKEY_HOST=rag-diary-valkey-1
      - VALKEY_PORT=6379

  valkey:
    image: valkey:8.0-alpine
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: "valkey-server --save 60 1 --loglevel warning --maxmemory-policy noeviction"

  postgres:
    image: pgvector:pg17
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  pg_data:
