services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:
