import localFont from "next/font/local";

import type { Metadata } from "next";

import "./globals.css";

import { Toaster } from "~/components/ui/sonner";

const gyonggiBatangFont = localFont({
  src: [
    {
      path: "./Batang_Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./Batang_Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${gyonggiBatangFont.className} antialiased`}>
        <main className="w-full">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
